USE IF6201_PV1_B97452_B80088
GO 

/*
	INSERTA EL PRODUCTO EN LA TABLA CATEGORIA
	 * VALIDA SI EL NOMBRE DE LA CATEGORIA EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1 
*/
CREATE PROCEDURE PRODUCTO.sp_INSERTAR_CATEGORIA
	@param_NOMBRE_CATEGORIA VARCHAR(24)
AS 
BEGIN 
	IF NOT EXISTS (SELECT [NOMBRE_CATEGORIA] FROM PRODUCTO.tb_CATEGORIA)
		BEGIN
			INSERT INTO PRODUCTO.tb_CATEGORIA
			(
				[NOMBRE_CATEGORIA]
			)
			VALUES
			(
				@param_NOMBRE_CATEGORIA
			)
			SELECT 1 AS RESPUESTA 
		END
	ELSE
		BEGIN
			SELECT 0 AS RESPUESTA
		END
END
GO

/*
	MODIFICA UNA CATEGORIA 
	* VALIDA SI EL NOMBRE DE LA CATEGORIA EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1 
*/
CREATE PROCEDURE PRODUCTO.sp_MODIFICAR_CATEGORIA
	@ID_CATEGORIA			INT,
	@param_NOMBRE_CATEGORIA VARCHAR(24)
AS
BEGIN
	IF NOT EXISTS (SELECT [NOMBRE_CATEGORIA] FROM [PRODUCTO].tb_CATEGORIA WHERE [NOMBRE_CATEGORIA] = @param_NOMBRE_CATEGORIA)
		BEGIN
			UPDATE PRODUCTO.tb_PRODUCTO
				SET NOMBRE = @param_NOMBRE_CATEGORIA
			WHERE @ID_CATEGORIA = @ID_CATEGORIA
			SELECT 1 AS RESPONSE
		END
	ELSE 
		BEGIN
			SELECT 2 AS RESPONSE
		END
END