USE IF6201_PV1_B97452_B80088
GO 

/*
	INSERTA EL PRODUCTO EN LA TABLA PRODUCTO
		* VALIDA SI EL NOMBRE DEL PRODUCTO EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1
*/
CREATE PROCEDURE PRODUCTO.sp_INSERTAR_PRODUCTO
	@param_NOMBRE			VARCHAR(68),
	@param_PRECIO			FLOAT,
	@param_RUTA_IMAGEN		VARCHAR(68),
	@param_STOCK			INT,
	@param_NOMBRE_CATEGORIA INT
AS
BEGIN 
	IF NOT EXISTS (SELECT [NOMBRE] FROM [PRODUCTO].[tb_PRODUCTO] WHERE NOMBRE = @param_NOMBRE)
		BEGIN
			DECLARE @local_ID_CATEGORIA INT = (SELECT	[ID_CATEGORIA]
													FROM [PRODUCTO].[tb_CATEGORIA]
														WHERE ID_CATEGORIA = @param_NOMBRE_CATEGORIA)
												
			INSERT INTO [PRODUCTO].[tb_PRODUCTO]
			(
				[NOMBRE], [PRECIO], [RUTA_IMAGEN], [STOCK], [ID_CATEGORIA]
			)
			VALUES
			(
				@param_NOMBRE,
				@param_PRECIO,
				@param_RUTA_IMAGEN,
				@param_STOCK, 
				@local_ID_CATEGORIA
			)
			SELECT 1 AS RESPUESTA
		END
	ELSE
		BEGIN
			SELECT 0 AS RESPUESTA
		END
END
GO

/*
	ELIMINA UN PRODUCTO SEGUN UN "ID"
	VALIDA SI EXISTE
*/
CREATE PROCEDURE [PRODUCTO].[sp_ELIMINAR_PRODUCTO]
	@param_ID_PRODUCTO INT
AS
BEGIN
	IF EXISTS (SELECT [NOMBRE] FROM [PRODUCTO].[tb_PRODUCTO] WHERE ID_PRODUCTO = @param_ID_PRODUCTO)
	BEGIN
		DELETE FROM PRODUCTO.tb_PRODUCTO
		WHERE ID_PRODUCTO = @param_ID_PRODUCTO
		SELECT 1 AS RESPONSE
	END
	ELSE
	BEGIN
		SELECT 2 AS RESPONSE
	END

END
GO

/*
	MODIFICA UN PRODUCTO 
	* VALIDA SI EL NOMBRE DEL PRODUCTO EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1
*/
CREATE PROCEDURE PRODUCTO.sp_MODIFICAR_PRODUCTO
	@param_ID_PRODUCTO		INT,	
	@param_NOMBRE			VARCHAR(68),
	@param_PRECIO			FLOAT,
	@param_RUTA_IMAGEN		VARCHAR(68),
	@param_STOCK			INT,
	@param_NOMBRE_CATEGORIA INT
AS
BEGIN
	IF EXISTS (SELECT [NOMBRE] FROM [PRODUCTO].[tb_PRODUCTO] WHERE ID_PRODUCTO = @param_ID_PRODUCTO)
		BEGIN
			DECLARE @local_ID_CATEGORIA INT = (SELECT [ID_CATEGORIA]
														FROM [PRODUCTO].[tb_CATEGORIA]
															WHERE ID_CATEGORIA = @param_NOMBRE_CATEGORIA)
			UPDATE PRODUCTO.tb_PRODUCTO
				SET NOMBRE = @param_NOMBRE,
					PRECIO = @param_PRECIO,
					RUTA_IMAGEN = @param_RUTA_IMAGEN,
					STOCK = @param_STOCK,
					ID_CATEGORIA = @local_ID_CATEGORIA
			WHERE ID_PRODUCTO = @param_ID_PRODUCTO
			SELECT 1 AS RESPONSE
		END
	ELSE 
		BEGIN
			SELECT 2 AS RESPONSE
		END
END
GO

/*
	MUESTRA TODOS LOS PRODUCTOS
*/
CREATE PROCEDURE PRODUCTO.OBTENER_PRODUCTOS
AS
BEGIN
	SELECT [ID_PRODUCTO], [NOMBRE], [PRECIO], [RUTA_IMAGEN], [STOCK], [ID_CATEGORIA] FROM [PRODUCTO].[tb_PRODUCTO]
END