CREATE DATABASE IF6201_PV1_B97452_B80088
GO 
USE IF6201_PV1_B97452_B80088
GO

CREATE SCHEMA PRODUCTO
GO

CREATE SCHEMA ADMIN
GO

CREATE TABLE PRODUCTO.tb_CATEGORIA
(
	ID_CATEGORIA     INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_CATEGORIA VARCHAR(24)
)
GO

CREATE TABLE PRODUCTO.tb_PRODUCTO
(
	ID_PRODUCTO  INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE		 VARCHAR(68),
	PRECIO		 FLOAT,
	RUTA_IMAGEN  VARCHAR(68),
	STOCK		 INT,
	ID_CATEGORIA INT,
	CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES PRODUCTO.tb_CATEGORIA(ID_CATEGORIA)
)
GO

CREATE TABLE ADMIN.tb_ADMNISTRADOR 
(
	ID_ADMIN	INT PRIMARY KEY IDENTITY(1,1), 
	NOMBRE		VARCHAR(48),
	APELLIDO	VARCHAR(48)
)
GO