USE IF6201_PV1_B97452_B80088
GO 

/*
	INSERTA EL PRODUCTO EN LA TABLA CATEGORIA
	 * VALIDA SI EL NOMBRE DE LA CATEGORIA EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1 
*/
CREATE PROCEDURE PRODUCTO.sp_INSERTAR_CATEGORIA
	@param_NOMBRE_CATEGORIA VARCHAR(24)
AS 
BEGIN 
	IF NOT EXISTS (SELECT [NOMBRE_CATEGORIA] FROM PRODUCTO.tb_CATEGORIA WHERE NOMBRE_CATEGORIA = @param_NOMBRE_CATEGORIA)
		BEGIN
			INSERT INTO PRODUCTO.tb_CATEGORIA
			(
				[NOMBRE_CATEGORIA]
			)
			VALUES
			(
				@param_NOMBRE_CATEGORIA
			)
			SELECT 1 AS RESPUESTA 
		END
	ELSE
		BEGIN
			SELECT 0 AS RESPUESTA
		END
END
GO

/*
	MODIFICA UNA CATEGORIA 
	* VALIDA SI EL NOMBRE DE LA CATEGORIA EXISTE: TRUE -> DEVUELVE 0 / FALSE -> DEVUELVE 1 
*/
CREATE PROCEDURE [PRODUCTO].[sp_MODIFICAR_CATEGORIA]
	@ID_CATEGORIA			INT,
	@param_NOMBRE_CATEGORIA VARCHAR(24)
AS
BEGIN
	IF NOT EXISTS (SELECT [NOMBRE_CATEGORIA] FROM [PRODUCTO].tb_CATEGORIA WHERE [NOMBRE_CATEGORIA] = @param_NOMBRE_CATEGORIA)
		BEGIN
			UPDATE PRODUCTO.tb_CATEGORIA
				SET NOMBRE_CATEGORIA = @param_NOMBRE_CATEGORIA
			WHERE ID_CATEGORIA = @ID_CATEGORIA
			SELECT 1 AS RESPONSE
		END
	ELSE 
		BEGIN
			SELECT 2 AS RESPONSE
		END
END

/*
	MUESTRA TODAS LAS CATEGORIAS
*/
CREATE PROCEDURE PRODUCTO.OBTENER_CATEGORIAS
AS
BEGIN
	SELECT [ID_CATEGORIA], [NOMBRE_CATEGORIA] FROM [PRODUCTO].[tb_CATEGORIA]
END


/*
	ELIMINAR CATEGORIA
	ASIGNA EL ID 1(NONE) DE CATEGORIA A LOS PRODUCTOS QUE TIENEN LA CATEGORIA A ELIMINAR
	*1 SI SE EILIMINÓ
	*0 SI NO SE ELIMINÓ
*/

CREATE PROCEDURE PRODUCTO.sp_ELIMINAR_CATEGORIA
@param_ID_CATEGORIA INT
AS
BEGIN

	IF (@param_ID_CATEGORIA = 1)
	BEGIN
		SELECT 0 AS RESPONSE
	END
	ELSE
	BEGIN
		UPDATE PRODUCTO.tb_PRODUCTO
		SET ID_CATEGORIA = 1
		WHERE ID_CATEGORIA = @param_ID_CATEGORIA

		DELETE PRODUCTO.tb_CATEGORIA
		WHERE ID_CATEGORIA = @param_ID_CATEGORIA

		SELECT 1 AS RESPONSE
	END

END