CREATE SCHEMA OMAZON

CREATE TABLE OMAZON.ROLE

(
	ID_ROLE INT PRIMARY KEY IDENTITY(1,1),
	TIPO_ROLE VARCHAR(30)

);

CREATE TABLE OMAZON.USUARIO
(
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_USUARIO VARCHAR(50),
	CONTRASENNA VARCHAR(50),
	ID_ROLE INT,
	CONSTRAINT FK_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES OMAZON.ROLE(ID_ROLE)
);

CREATE TABLE OMAZON.TARJETA_CREDITO
(
	ID_TARJETA INT PRIMARY KEY IDENTITY(1,1),
	DIRECCION VARCHAR(300),
	NUMERO_TARJETA VARCHAR,
	CVV INT,
	FECHA_VENCIMIENTO  VARCHAR(30)
);

CREATE TABLE OMAZON.TARJETA_CREDITO_CLIENTE
(
	ID_TARJETA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT PK_TARJET_CLIENTE PRIMARY KEY (ID_TARJETA,ID_CLIENTE),
	CONSTRAINT FK_ID_TARJETA FOREIGN KEY (ID_TARJETA) REFERENCES OMAZON.TARJETA_CREDITO(ID_TARJETA),
	CONSTRAINT FK_ID_CLIENTE_TARJETA FOREIGN KEY (ID_CLIENTE) REFERENCES OMAZON.USUARIO(ID_USUARIO)
);

CREATE TABLE OMAZON.PROVEEDOR
(
	ID_PROVEEDOR INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL
);

CREATE TABLE OMAZON.PRODUCTO
(
	ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO VARCHAR(30) NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	CONSTRAINT FK_ID_PROVEEDOR_PRODUCTO FOREIGN KEY (ID_PROVEEDOR) REFERENCES OMAZON.PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE OMAZON.CARRITO_COMPRAS
(
	ID_CARRITO_COMPRAS  INT PRIMARY KEY IDENTITY(1,1),
	CANTIDAD INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CONSTRAINT FK_ID_CLIENTE_CARRITO FOREIGN KEY (ID_CLIENTE)   REFERENCES
	OMAZON.USUARIO(ID_USUARIO),
	SUB_TOTAL VARCHAR(30),
	CONSTRAINT FK_ID_PRODUCTO_CARRITO FOREIGN KEY (ID_PRODUCTO) REFERENCES OMAZON.PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE OMAZON.CLAVE_ACCESO
(	ID_CLAVE_ACCESO INT PRIMARY KEY IDENTITY(1,1),
	ID_PROVEEDOR INT,
	NUMERO_CLAVE VARCHAR(50),
	CONSTRAINT FK_ID_PROVEEDOR_CLAVE FOREIGN KEY (ID_PROVEEDOR) REFERENCES OMAZON.PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE OMAZON.PROVEEDOR_PRODUCTO
(
	ID_PROVEEDOR INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CONSTRAINT PK_ID_PROVEEDOR_PRODUCTO PRIMARY KEY (ID_PROVEEDOR,ID_PRODUCTO),
	CONSTRAINT FK_ID_PROVEEDOR_PROD FOREIGN KEY (ID_PROVEEDOR) REFERENCES OMAZON.PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_ID_PRODUCTO_PROVEEDOR FOREIGN KEY (ID_PRODUCTO) REFERENCES OMAZON.PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE OMAZON.COMPRA
(
	ID_COMPRA INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	TOTAL VARCHAR(50) NOT NULL,
	CONSTRAINT FK_ID_CLIENTE_COMPRA FOREIGN KEY (ID_CLIENTE) REFERENCES OMAZON.USUARIO(ID_USUARIO),
	CONSTRAINT FK_ID_PRODUCTO_COMPRA  FOREIGN KEY (ID_PRODUCTO ) REFERENCES  OMAZON.PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE OMAZON.BLOQUEADO
(
	ID_BLOQUEADO INT IDENTITY(1,1),
	ID_PRODUCTO INT NOT NULL,
	CONSTRAINT FK_ID_PRODUCTO_BLOQUEADO FOREIGN KEY (ID_PRODUCTO) REFERENCES OMAZON.PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE OMAZON.VENTA
(
	ID_VENTA INT PRIMARY KEY IDENTITY(1,1),
	ID_COMPRA INT NOT NULL,
	MONTO_TOTAL VARCHAR(32) NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	CONSTRAINT FK_COMPRA_VENTA FOREIGN KEY (ID_COMPRA) REFERENCES OMAZON.COMPRA(ID_COMPRA)
);

CREATE TABLE OMAZON.COMISION
(
	ID_COMISION INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_VENTA INT NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	MONTO VARCHAR(50) NOT NULL,
	CONSTRAINT FK_ID_PROVEEDOR_COMISION FOREIGN KEY (ID_PROVEEDOR) REFERENCES OMAZON.PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_ID_VENTA_COMISION  FOREIGN KEY (ID_VENTA ) REFERENCES OMAZON.VENTA(ID_VENTA )
);
